### ISSUE TITLE
Unchecked exceptions

### ISSUE THREAD

**Issue by DanielNovak** [instacart/truetime-android#11]
The `SntpClient.requestTime()` can throw a RuntimeException() in case the response from the server is not correct and as far as I can tell this exception isn't handled anywhere and it's not documented. So it can crash the whole app just because some input from the server was not as expected. I think there should be a error callback or other mechanism that is transparent for the end developer.

**Comment by kaushikgopal** [comment]
@DanielNovak good catch! 

_We've been battle testing `TrueTimeRx` more and those get surfaced elegantly with the Rx `onError` callbacks. So this didn't spring up._

Ok, so what would be an acceptable fix. I'm thinking:

* throw an `IOException` instead of RuntimeException. if you implement TrueTime java will force you to handle the IOException at call time.
* possibly add more documentation on the checks we do to make sure the server response is valid?

thoughts?

**Comment by sebaslogen** [comment]
I'm curious, why did you choose to use flatMap? You could have avoided the flatMap by using Exception.propagate(e)

**Comment by kaushikgopal** [comment]
@sebaslogen : totally could use `map` too.

(i think) i started off in another branch with the more stringent checks. and some of those exceptions were `RuntimeException`s. so they were unchecked. But subsequently i changed it to extend `IOException` and i just left it as `flatMap`. But given that everything is checked at this point, i could totally use `map` in combination with `Exceptions.propogate`
