### ISSUE TITLE
Invalid response from NTP server. Root delay violation 1828

### ISSUE THREAD

**Issue by ersin-ertan** [instacart/truetime-android#26]
Seems like a standard use case, but it's not working.
```java
public class MainActivity extends AppCompatActivity {

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    new AsyncTask<Void, Void, Void>() {
      @Override protected Void doInBackground(Void... params) {
        try {
          TrueTime.build()
              .withLoggingEnabled(true)
              .withSharedPreferences(MainActivity.this)
              .initialize();
        } catch (IOException e) {
          e.printStackTrace();
        }
        return null;
      }
    }.execute();

    setContentView(R.layout.activity_main);

    Button b = (Button) findViewById(R.id.button);
    b.setOnClickListener(new View.OnClickListener() {
      @Override public void onClick(View v) {
        if (TrueTime.isInitialized()) {
          Toast.makeText(MainActivity.this, TrueTime.now().toString(), Toast.LENGTH_SHORT).show();
        }
      }
    });
  }
}
```
[LookAtTheCrashReport.txt](https://github.com/instacart/truetime-android/files/538872/error.txt)

**Comment by mlilienberg** [comment]
Same problem here. Even the example app throws the same error. Currently I would not trust this library enough to use it in production environments.

**Comment by ersin-ertan** [comment]
This would lead me to question the importance(precision/accuracy considerations) of choosing the right geographical ntp server. If I'm getting timeouts hitting US servers, does this mean that an international app would require you to target servers within your timezone and compare the latency between the responses?

**Comment by kaushikgopal** [comment]
the root delay/dispersion issue was raised by folks before so i updated the README to explain why this happens, and how we handle it.

https://github.com/instacart/truetime-android/blob/master/README.md#troubleshootigexception-handling

**Comment by kaushikgopal** [comment]
@ersin-ertan great question! some thoughts that should (hopefully) in summation answer that question : 

* with the 2.0 release, I changed the Rx api to hit a single NTP "pool" host and resolve that to get multiple IP server hosts. each NTP pool host uses a different algorithm for "synchronizing" the time across individual server hosts. that's why the NTP spec recommends hitting a single NTP pool vs hitting multiple pools.



I cannot say for certain but from my readings online, they recommend picking a pool closest geographically. I imagine this is for the same reason.

**Comment by kaushikgopal** [comment]
@ersin-ertan great question! some thoughts that should (hopefully) in summation answer that question :

* with the 2.0 release, I changed the Rx api to hit a single NTP "pool" host and resolve that to get multiple IP server hosts. each NTP pool host uses a different algorithm for "synchronizing" the time across individual server hosts. that's why the NTP spec recommends hitting a single NTP pool vs hitting multiple pools.
* I cannot say for certain but from my readings online, they recommend picking a pool closest geographically. I imagine this is for the same reasons like picking the closest CDN ¯\_(ツ)_/¯
* Much like our beloved epoch `Date` objects, NTP also maintains time with reference to it's own epoch, so there's no clear notion of timezone. Because of this, i don't belive there's a requirement to target servers in your same timezone.

**Comment by toddhodes** [comment]
unfortunately, I can't have my company's app logging errors for a case that is "very highly likely".  (this is probably not even a proper Exception(al) condition.)  are you willing to log this at DEBUG instead?  or add an option to turn off the logging of this case?  i can simply fork the repo, but, that is a pain..

**Comment by javaboboApp** [comment]
Hi I am getting same error https://github.com/instacart/truetime-android/blob/master/README.md#troubleshootigexception-handling is not available anymore..

**Comment by javaboboApp** [comment]
@kaushikgopal

**Comment by kaushikgopal** [comment]
@javaboboApp I just merged a new alpha version of the library. There's a **lot** of changes in the APIs. I'd encourage folks to start taking a look at the new apis.
