### ISSUE TITLE
Valid once per boot even for uptimes measured in weeks or more?

### ISSUE THREAD

**Issue by CantStopMyBrain** [instacart/truetime-android#84]
The readme says "Also, once we have this information it's valid until the next time you boot your device."

Is this true regardless of system uptime? I have no real feel (nor data) for the drift of the system clock on a typical android device, but I worry that it could be on order of seconds/month. We need the (ongoing) best accuracy obtainable for remotely-deployed devices with uptimes of weeks to months. Would a periodic re-sync be advisable? If so, can I simply call initializeRx() again or do I need to do more to ensure it doesn't just pull from cache?

Thanks for this awesome library... my first exposure to reactive code and it's blowing my mind (in a good way).

Chris

**Comment by niklasdahlheimer** [comment]
Hey Chris,

I did a few investigations about the time drift of android devices for my thesis and it's definitly a problem: For example a Samsung Galaxy A3 was drifting around **40ms/h**. That's almost a second per day.

In a test app I called `initializeRx()` once every 4 hours and it gave me a good picture of the drift of the devices. The plots had only a little deviation because of the NTP-Update uncertainties, but apart from that it where lines with a constant slope.

So, yes, clock drift is a thing and yes, I guess you can call `initializeRx()` in poll intervalls (at least I just did :) ).

But I would also really love to **have a clearification from the developers** about

> [...] we go all the way and implement the full NTP [...]

in the Readme, because, in my understanding, NTP does not only query the time from a pool of servers and select the best result once, it also updates the time in poll intervalls and implements a Frequency Locked Loop to compensate the drift of the clock.
At least the Linux implementation ntpd provides a driftfile. where ntpd saves a calculated drift of the systemclock.


Besides that, a big **thank you** to the developers for a great library :)

[Understanding the driftfile](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-understanding_the_drift_file)
[Clock Discipline Algorithm](https://www.eecis.udel.edu/~mills/ntp/html/discipline.html)

**Comment by niklasdahlheimer** [comment]
Hey Chris,
I'm totally with you! I never thought that TrueTime is actually changing the system time (tough this can not be done without root access I guess). I think a better formulation is:

**"is TrueTime tuning the offset between the monotronic uptime of the device and it's NTP-queried time to compensate potential drift resulting from a variance of the smartphones internal time curcuit OR is it (just) setting a constant offset to the (monotronic) system time every time `InitializeRx()` is called??"**

**Comment by CantStopMyBrain** [comment]
I believe it's the latter (though the former would be preferable); don't your results ("...I called initializeRx() once every 4 hours and it gave me a good picture of the drift...") pretty much answer the question already, or am I misunderstanding something?

Hopefully we'll be getting some reliable input from the author very soon now.

**Comment by niklasdahlheimer** [comment]
You are right, probably the results already answered the question. But why trust (maybe for some reason I don't know faulty) test-results if you could get a clear and proving statement from a developer? So I'm looking forward to get this :)

**Comment by kaushikgopal** [comment]
hey @CantStopMyBrain + @niklasdahlheimer - sorry I couldn't reply earlier. Here's a confirmation/response to some of the points raised above:

> Would a periodic re-sync be advisable? If so, can I simply call initializeRx() again or do I need to do more to ensure it doesn't just pull from cache?

💯. a periodic re-sync is actually very much needed :). I think this was organically raised in ☝️ thread but TrueTime basically gets the offset from the "true" time; at that instant. Clock drifts is a real problem and so that means, over time, it's definitely going to go out of sync again with the "true" time. This is a physical limitation of the oscillator crystal in CPUs which help keep time.

For our application, we have another observable that runs at regular intervals, which "re-syncs" at regular intervals. If you're curious I can share the code snippet here. also opened an issue #91 for this.

> > [...] we go all the way and implement the full NTP [...]
> At least the Linux implementation ntpd provides a driftfile. where ntpd saves a calculated drift of the systemclock.
> TrueTime/TrueTimeRx does not try to change the system time. By "full NTP", I think the author is referring only to the communication with NTP servers: in contrast to SNTP, which only uses a single NTP server, the "full NTP" protocol sends multiple queries to multiple servers and follows a particular algorithm for processing the results to get the best estimate for the "true time".

💯 . This was the intention with that statement :)

**Comment by kaushikgopal** [comment]
> "is TrueTime tuning the offset between the monotronic uptime of the device and it's NTP-queried time to compensate potential drift resulting from a variance of the smartphones internal time curcuit OR is it (just) setting a constant offset to the (monotronic) system time every time InitializeRx() is called??"

It's just the latter. In fact @msanders who maintains the Swift version of our library and I talked about maybe dealing with the former too, but if we're being honest, at the moment for our specific use case, the accuracy levels are pretty decent. Maybe in a future version, but to answer the question it's definitely just the latter with the library.

**Comment by CantStopMyBrain** [comment]
Thanks for the clarifications. So re-sync can be a simple call to initializeRx()? Nothing to tear down first or settings to make to avoid memory leaks and avoid pulling from the TrueTime cache rather than doing a fresh NTP sync?
Code snippets appreciated -- I'll monitor #91 for that.
Thanks again.

**Comment by kaushikgopal** [comment]
added the note in the wiki @CantStopMyBrain. Hope that clarifies it.

Typically you do all of the initialization in an application `onCreate` "once" (the sample code snippets should help explain it more clearly), so there isn't a danger necessarily of it leaking, but it is something that will constantly run forever but that should be ok (for the time accuracy). 

Also the actual init call is a `Single` that should eventually complete, so no trouble there.

Closing this out, let me know if more info is needed
