### ISSUE TITLE
TrueTimeRx subscribe only called once

### ISSUE THREAD

**Issue by scottybe** [instacart/truetime-android#90]
I feel kind of embarrassed to be asking, since I imagine the solution is obvious to many.

In my Activity's OnCreate function, I set up a subscription in the following way:

           trueTimeRxObservable.subscribe(new Subscriber<Date>() {
                @Override
                public void onNext(Date t) {
                    Log.i("truetime", "got new time!");
                }
            });

However, onNext is only called once. Shouldn't onNext get called every time there's a new adjustment to the "true" time? If not, how can I get notified of these updates like the "TrueTimeUpdatedNotification" on the Swift version? Thanks!

**Comment by kaushikgopal** [comment]
@scottybe not at all. This is actually a great question. Here's some thoughts that should help answer the question:

* In your question is `trueTimeRxObservable` = `TrueTimeRx.build().initializeRx()` ?  If yes, then basically the initialization is done only once. So you probably wouldn't be expecting an observable of TrueTime updates.
* Probably makes sense semantically to use a `Single` here instead of an `Observable` 🤔. Typically having an Observable is more flexible than a `Single` so I left it as an Observable, but I'm reconsidering that now as it would make it more clear. hmmm. 

>  Shouldn't onNext get called every time there's a new adjustment to the "true" time? If not, how can I get notified of these updates

Also a very good question. In most of my usage of this, I have a simple `Observable.interval` like operator that repeatedly re-reruns the initialization process which helps with the accuracy. 

It might actually make sense though to expose this as an api to, which would make consuming the library even more simpler.

Hope that answers your questions. 

For my own understanding two suggestions come out of this:

1. convert the Observable init process to maybe a Single
2. provide an api that runs in the background constantly retrying the init call

**Comment by kaushikgopal** [comment]
So I was speaking from memory of an old codebase :P. If you notice, we currently only expose a `Single` so 1 has already been resolved :). We don't return Observable, just Singles which should make it more clear.

**Comment by scottybe** [comment]
Thanks, Kaushikgopal. I'll be checking [https://github.com/instacart/truetime-android/issues/91](url)!

**Comment by niklasdahlheimer** [comment]
Hey!
In experiments from [these ](https://link.springer.com/chapter/10.1007/978-3-319-14445-0_18) guys the time drift was between 3 ppm (Asus Nexus 7 2012 Wi-Fi) and 270 ppm (Samsung Galaxy SII ).
So that means, if you want to stay in the 2 second window you would need to update the time every 2 hours:

270ppm = 270s / 1.000.000s = 1s / 3703s = 1s / 61,7min 
-> 2s / 2h

**Comment by scottybe** [comment]
Or update every 12 minutes to stay within 2/10 of a second: ,2s / 12,34min.

Thanks!

**Comment by niklasdahlheimer** [comment]
Oh right, yes, I overlooked your dot, sorry. (German people are not used to dots instead of commas as decimal-separators and ignore them sometimes :D )

**Comment by kaushikgopal** [comment]
Added a wiki on how we go about setting the interval.

Honestly we chose an interval of 5 minutes with very rudimentary trial and error with our app usage. We found 5 minutes to be a decent balance, but I'd now rely more on the data that @niklasdahlheimer and you @scottybe have brought up in this thread.

Adding your notes in the wiki :) (also feel free to edit that Wiki if you have more pertinent information)

**Comment by niklasdahlheimer** [comment]
Hey Kaushik,
If you like, you could use the tests below for the wiki too.I think I have no permissions to edit the wiki, so I can not add it by myself.

TestDevices:
Test-Device 1 | Samsung Galaxy A3 (2017)   (SM-A320FL) | Android 8.0.0   (API-Level 26)
Test-Device 2 | Samsung Galaxy Tab A (2016)   (SM-T580) | Android 7.0   (API-Level 24)
Test-Device 3 | Fairphone 2 (2015)   (FP2) | Android 6.0.1   (API-Level 23)

The tests are made over WLAN with an 20mbit-DSL-internet-connection.

The first test shows the TrueTime-update-offset for device 1 with an update interval of 10min. 

The second test shows the TrueTime-update-offsets for all three devices over 12 hours with one update per hour.

I can not translate all my conclusions here, but maybe the plots will provide substance for the people who want to dig in into the field of offsets and drifts :)

![offset 1](https://user-images.githubusercontent.com/36920541/45216099-b3bf4100-b29f-11e8-9334-4bd1b4900fdc.png)
![offset and drift](https://user-images.githubusercontent.com/36920541/45216100-b3bf4100-b29f-11e8-9334-ffa54cee3f26.png)

**Comment by kaushikgopal** [comment]
@niklasdahlheimer this is brilliant. I just opened up permissions to the wiki, please edit it directly, would prefer you get credit for this :).

Thanks for the super helpful info.
